### ISSUE TITLE
Search controller

### ISSUE THREAD

**Issue by dougmet** [MangoTheCat/rcloud.solr#35]
Big feature.

Add a controller to sit inbetween searches and solr. It will grab a large number of search results and control:

- [x] create test second solr instance #38 
- [x] store results from all sources #39 
- [x] sort results #40
- [x] implement paging #43 
- [x] invalidate cache
- [x] sort dates and chars #46

Things to consider:

This is ultimately all about combining multiple sources, so bare that in mind when designing this. One source is main, there may be many alternative sources.

**Comment by dougmet** [comment]
In the first iteration we're going to go for the following behaviour:

`page: 0` indicates a new search. cache is discarded and new searches made against solr.
`page: >0` indicates paging through an old search. Cache doesn't get invalidated.

Need to think about circumstances whereby cache should be invalidated (and trigger a new search) when `page>0`.
